apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-agent

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sre-agent

  template:
    metadata:
      labels:
        app: sre-agent

    spec:
      containers:
      - name: agent
        image: dinesh200625/sre-agent:latest

        env:
        - name: JENKINS_USER
          value: "admin"

        - name: JENKINS_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: sre-agent-secrets
              key: jenkins-api-token

        - name: AI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sre-agent-secrets
              key: groq-api-key